version: '3.9'
services:
  streamlit:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: streamlit-gcp-example
    cpus: 2
    mem_limit: 2048m
    ports:
      - "8501:8080"
    volumes:
      - ".:/app:rw"
